spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

springdoc:
  swagger-ui:
    enabled: false

app:
  security:
    username: ${APP_SECURITY_USERNAME}
    password: ${APP_SECURITY_PASSWORD}
    role: ${APP_SECURITY_ROLE:STUDENT}

management:
  endpoint:
    health:
      show-details: never
